before_script: "cd test_app && bundle install && ./script/rails generate impressionist && bundle exec rake db:migrate"
env: "RAILS_ENV=test"
language: ruby
rvm:
  - 1.9.3
script: "cd ../ && bundle exec rake"
